<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>54 ahh</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>13</LastSerialNumber>
            <Stage3Mass>834.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>390.0</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>1</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>58.76717336450929</KnownMass>
                    <Density>2700.0</Density>
                    <Material>Aluminum</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>79.87233750000001</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>58.76717336450929</CalcMass>
                    <CalcCG>79.87233750000001</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>106.50000000000001</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>0</ConstructionType>
                    <WallThickness>13.97</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>27.94</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>0.0</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>0.05</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>0.0</CalcMass>
                    <CalcCG>0.05</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>0.1</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>27.94</OD>
                    <ID>27.94</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>27.94</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <Transition>
                    <KnownMass>135.5</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Transition</Name>
                    <KnownCG>192.13155303316523</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>153.6406144630984</CalcMass>
                    <CalcCG>192.13155303316523</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>296.00000000000006</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>3</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.6509999999999998</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>198.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>133.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>133.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>45.0</KnownMass>
                            <Density>0.00341</Density>
                            <Material>Nylon fabric, ripstop, 1.1 oz actual</Material>
                            <Name>Parachute, 30 in., nylon, thin mill, 8 lines</Name>
                            <KnownCG>62.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-20.00000000000001</Xb>
                            <CalcMass>19.70614562144141</CalcMass>
                            <CalcCG>62.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>125.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <Dia>609.5999999999999</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>762.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0016</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 110 lb, 1/16 in. dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>80.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>56.2</RearShoulderDia>
                    <FrontDia>27.94</FrontDia>
                    <RearDia>55.99999999999999</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>0.0</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>40.00000000000002</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>33.57923518312741</CalcMass>
                    <CalcCG>40.00000000000002</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>80.00000000000004</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>6</SerialNo>
                    <OD>55.99999999999999</OD>
                    <ID>53.358399999999996</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>53.358399999999996</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <Transition>
                    <KnownMass>2.884428659092432</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Transition</Name>
                    <KnownCG>6.31006222203584</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>2.884428659092432</CalcMass>
                    <CalcCG>6.31006222203584</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>12.7</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>7</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>55.99999999999999</FrontDia>
                    <RearDia>54.00000000000001</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>0.0</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>182.8</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>0.0</CalcMass>
                    <CalcCG>182.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>365.6</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>8</SerialNo>
                    <OD>54.00000000000001</OD>
                    <ID>54.00000000000001</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>54.00000000000001</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <Transition>
                    <KnownMass>2.8916700549435936</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Transition</Name>
                    <KnownCG>6.393849884139768</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>2.8916700549435936</CalcMass>
                    <CalcCG>6.393849884139768</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>12.7</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>9</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>54.00000000000001</FrontDia>
                    <RearDia>56.2</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>85.6032270258743</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>101.6</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>85.6032270258743</CalcMass>
                    <CalcCG>101.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>203.2</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>10</SerialNo>
                    <OD>56.2</OD>
                    <ID>53.5584</ID>
                    <IsMotorMount>1</IsMotorMount>
                    <MotorDia>53.5584</MotorDia>
                    <EngineOverhang>20.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>220.8406335045911</KnownMass>
                            <Density>1780.0</Density>
                            <Material>Carbon fiber</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>101.38781750698409</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>220.8406335045911</CalcMass>
                            <CalcCG>101.38781750698409</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>11</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>170.0</RootChord>
                            <TipChord>30.0</TipChord>
                            <SemiSpan>60.0</SemiSpan>
                            <SweepDistance>134.99999999999997</SweepDistance>
                            <Thickness>4.0</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>60.00000000000001</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>0.0</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>10.000000000000018</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>0.0</CalcMass>
                    <CalcCG>10.000000000000018</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>20.000000000000036</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>12</SerialNo>
                    <OD>56.2</OD>
                    <ID>56.2</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>56.2</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <Transition>
                    <KnownMass>7.6702236678962485</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Transition</Name>
                    <KnownCG>17.146099884802787</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>7.6702236678962485</CalcMass>
                    <CalcCG>17.146099884802787</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>35.000000000000014</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>13</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>56.2</FrontDia>
                    <RearDia>50.0</RearDia>
                </Transition>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>