<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>17</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>696.8196509466036</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>58.605578215739754</KnownMass>
                    <Density>1050.0</Density>
                    <Material>Polystyrene, cast, bulk</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>58.605578215739754</CalcMass>
                    <CalcCG>174.75240021753345</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>279.4</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.27</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>100.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>50.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>50.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>76.19999999999999</BaseDia>
                    <ShoulderLen>76.19999999999999</ShoulderLen>
                    <ShoulderOD>74.3458</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>38.22658855625548</KnownMass>
                    <Density>894.4</Density>
                    <Material>Paper, spiral kraft glassine, BMS avg, bulk</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>38.22658855625548</CalcMass>
                    <CalcCG>101.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>203.2</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>3</SerialNo>
                    <OD>76.19999999999999</OD>
                    <ID>74.422</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>74.422</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <BodyTube>
                    <KnownMass>19.11329427812774</KnownMass>
                    <Density>894.4</Density>
                    <Material>Paper, spiral kraft glassine, BMS avg, bulk</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>19.11329427812774</CalcMass>
                    <CalcCG>50.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>101.6</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>76.19999999999999</OD>
                    <ID>74.422</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>74.422</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>46.9889794237879</KnownMass>
                            <Density>1126.0</Density>
                            <Material>Paper, spiral kraft, BMS C300, bulk</Material>
                            <Name>Tube Coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-50.8</Xb>
                            <CalcMass>46.9889794237879</CalcMass>
                            <CalcCG>101.6</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>203.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>74.422</OD>
                            <ID>72.644</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>6.847251984946329</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Bulkhead0.5</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>426.79999999999995</Xb>
                            <CalcMass>6.847251984946329</CalcMass>
                            <CalcCG>1.25</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>2.5</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>74.4</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>6.847251984946329</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Bulkhead0.5</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>637.5</Xb>
                            <CalcMass>6.847251984946329</CalcMass>
                            <CalcCG>1.25</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>2.5</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>74.4</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>100.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>10.000000000000046</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>10.000000000000046</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>85.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>124.23641280783004</KnownMass>
                    <Density>894.4</Density>
                    <Material>Paper, spiral kraft glassine, BMS avg, bulk</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>124.23641280783004</CalcMass>
                    <CalcCG>330.2</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>660.4</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>9</SerialNo>
                    <OD>76.19999999999999</OD>
                    <ID>74.422</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>74.422</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>53.56089062511872</KnownMass>
                            <Density>894.4</Density>
                            <Material>Paper, spiral kraft glassine, BMS avg, bulk</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-25.400000000000002</Xb>
                            <CalcMass>53.56089062511872</CalcMass>
                            <CalcCG>170.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>340.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>41.528999999999996</OD>
                            <ID>38.735</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>38.735</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Parachute>
                            <KnownMass>46.31203545637582</KnownMass>
                            <Density>0.00527</Density>
                            <Material>Nylon fabric, ripstop, 1.7 oz actual</Material>
                            <Name>Parachute, 36 in., nylon, 8 lines</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>80.0</Xb>
                            <CalcMass>46.31203545637582</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>2.8210926670778784</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Dia>914.4</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>914.4</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0016</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 110 lb, 1/16 in. dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <Parachute>
                            <KnownMass>13.041048864093954</KnownMass>
                            <Density>0.00527</Density>
                            <Material>Nylon fabric, ripstop, 1.7 oz actual</Material>
                            <Name>Parachute, 18 in., nylon, 6 lines</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>80.0</Xb>
                            <CalcMass>13.041048864093954</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>2.8210926670778784</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <Dia>457.2</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>457.2</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0016</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 110 lb, 1/16 in. dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>10.18466578407858</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Centering Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>10.18466578407858</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>74.422</OD>
                            <ID>41.528999999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>12.934525545779797</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Centering Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>300.0</Xb>
                            <CalcMass>12.934525545779797</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>74.422</OD>
                            <ID>41.528999999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <FinSet>
                            <KnownMass>154.18662584</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>5.0</Xb>
                            <CalcMass>154.18662584</CalcMass>
                            <CalcCG>84.19854665132742</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>15</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>140.0</RootChord>
                            <TipChord>60.000000000000014</TipChord>
                            <SemiSpan>65.0</SemiSpan>
                            <SweepDistance>85.0</SweepDistance>
                            <Thickness>6.35</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>140.0</TabLength>
                            <TabDepth>17.335499999999996</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <Ring>
                            <KnownMass>5.09233289203929</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Centering Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>149.99999999999994</Xb>
                            <CalcMass>5.09233289203929</CalcMass>
                            <CalcCG>1.25</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>2.5</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <OD>74.422</OD>
                            <ID>41.528999999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>3.4046784104575267</KnownMass>
                    <Density>310.0</Density>
                    <Material>PLA 20% infill</Material>
                    <Name>Transition</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>3.4046784104575267</CalcMass>
                    <CalcCG>12.031447392834615</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>25.4</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>17</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.9999999999999996</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>76.19999999999999</FrontDia>
                    <RearDia>55.99999999999999</RearDia>
                </Transition>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>