<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>11</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>309.52395800559316</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>13.000000000000002</KnownMass>
                    <Density>245.0</Density>
                    <Material>3d printed ribbed body tube</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>6.372371176910574</CalcMass>
                    <CalcCG>79.62919168918414</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>127.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.0</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>76.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Flight Computer</Name>
                            <KnownCG>130.00000000000003</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>130.00000000000003</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>220.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>61.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass Component</Name>
                            <KnownCG>30.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>30.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>50.8</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>44.8</KnownMass>
                    <Density>245.0</Density>
                    <Material>3d printed ribbed body tube</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>111.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>19.08092793729037</CalcMass>
                    <CalcCG>111.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>254.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>50.8</OD>
                    <ID>46.8</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>46.8</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>3.604185888645588</KnownMass>
                            <Density>310.0</Density>
                            <Material>PLA 20% infill</Material>
                            <Name>Tube Coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-30.0</Xb>
                            <CalcMass>3.604185888645588</CalcMass>
                            <CalcCG>20.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>40.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>48.26</OD>
                            <ID>44.25999999999999</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>84.0</KnownMass>
                    <Density>245.0</Density>
                    <Material>3d printed ribbed body tube</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>114.3</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>14.723865652397297</CalcMass>
                    <CalcCG>114.3</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>196.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>6</SerialNo>
                    <OD>50.8</OD>
                    <ID>46.8</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>46.8</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>2.8352816992900483</KnownMass>
                            <Density>310.0</Density>
                            <Material>PLA 20% infill</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>50.0</Xb>
                            <CalcMass>2.8352816992900483</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>48.26</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>2.202218071762794</KnownMass>
                            <Density>0.00117</Density>
                            <Material>Polyethylene film, HDPE, 0.50 mil, bare</Material>
                            <Name>Parachute, 24 in., polyethylene, 0.5 mil, 8 lines</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>2.202218071762794</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>7.133921396741912</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <Dia>457.2</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>609.5999999999999</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>5.77E-5</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon thread, rod wrapping, size D</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <FinSet>
                            <KnownMass>8.707279999999999</KnownMass>
                            <Density>310.0</Density>
                            <Material>PLA 20% infill</Material>
                            <Name>Main Fin Set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>8.707279999999999</CalcMass>
                            <CalcCG>52.21541820943701</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>9</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>90.0</RootChord>
                            <TipChord>50.0</TipChord>
                            <SemiSpan>40.0</SemiSpan>
                            <SweepDistance>40.0</SweepDistance>
                            <Thickness>2.0</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>90.0</TabLength>
                            <TabDepth>7.899999999999998</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>10.225884087434778</KnownMass>
                            <Density>310.0</Density>
                            <Material>PLA 20% infill</Material>
                            <Name>Motor Tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>10.225884087434778</CalcMass>
                            <CalcCG>35.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>70.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>35.0</OD>
                            <ID>25.0</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>25.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>2.4293778910577184</KnownMass>
                                    <Density>310.0</Density>
                                    <Material>PLA 20% infill</Material>
                                    <Name>Engine Block</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>-5.0</Xb>
                                    <CalcMass>2.4293778910577184</CalcMass>
                                    <CalcCG>2.5</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>5.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>11</SerialNo>
                                    <OD>48.26</OD>
                                    <ID>18.259999999999998</ID>
                                    <UsageCode>2</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>